/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Bloodbank;

import Business.Blood.BloodGroup;
import Business.Blood.BloodGroupList;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.ClinicianOrganization;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BloodReqToNewBB;
import Business.WorkQueue.BloodrequestToBBfromHospital;
import Business.WorkQueue.WorkRequest;
import static Logger.Logger.logger;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harshi
 */
public class HospitalReqJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospitalReqJPanel
     */
    private JPanel userProcessContainer;
    private ClinicianOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private BloodGroup bloodgroup;
    private BloodGroupList bloodgrouplist;
    private EcoSystem ecosystem;
    private Network network;
    private Enterprise.EnterpriseType enterprisetype;
    private OrganizationDirectory organizationdirectory;

    public HospitalReqJPanel(JPanel userProcessContainer, BloodGroup bloodgroup, BloodGroupList bloodgrouplist, Enterprise enterprise, UserAccount userAccount, EcoSystem ecosystem) {
        logger.log(Level.INFO, "HospitalReqJPanel");

        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.bloodgroup = bloodgroup;
        this.bloodgrouplist = bloodgrouplist;
        this.network = network;
        this.ecosystem = ecosystem;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.enterprisetype = enterprisetype;
        this.organization = organization;
        this.organizationdirectory = organizationdirectory;

        populateBloodReqTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        bloodReqTable = new javax.swing.JTable();
        assignJButton = new javax.swing.JButton();
        btnAccept = new javax.swing.JButton();
        btnDecline = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        manageEnt2 = new javax.swing.JLabel();
        manageEnt3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bloodReqTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Blood Group", "No of Units", "Request Status", "Assigned To", "Requested Hospital"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(bloodReqTable);
        if (bloodReqTable.getColumnModel().getColumnCount() > 0) {
            bloodReqTable.getColumnModel().getColumn(0).setResizable(false);
            bloodReqTable.getColumnModel().getColumn(1).setResizable(false);
            bloodReqTable.getColumnModel().getColumn(2).setResizable(false);
            bloodReqTable.getColumnModel().getColumn(3).setResizable(false);
            bloodReqTable.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 659, 143));

        assignJButton.setText("Assign to me");
        assignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignJButtonActionPerformed(evt);
            }
        });
        add(assignJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });
        add(btnAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, -1, -1));

        btnDecline.setText("Decline");
        btnDecline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeclineActionPerformed(evt);
            }
        });
        add(btnDecline, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, -1, -1));

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, -1, -1));

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        manageEnt2.setFont(new java.awt.Font("Tamil MN", 0, 14)); // NOI18N
        manageEnt2.setText("Hospital Requests:");
        add(manageEnt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 250, -1));

        manageEnt3.setFont(new java.awt.Font("Tamil MN", 1, 18)); // NOI18N
        manageEnt3.setText("CLINICIAN REQUEST AREA");
        add(manageEnt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 250, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void populateBloodReqTable() {
        logger.log(Level.INFO, "populateBloodReqTable --HospitalReqJPanel");

        DefaultTableModel model = (DefaultTableModel) bloodReqTable.getModel();

        model.setRowCount(0);

        for (WorkRequest workreq : enterprise.getWorkQueue().getWorkRequestList()) {
            if (workreq.getClass().getName().contains("BloodrequestToBBfromHospital")) {
                Object[] row = new Object[5];
                row[0] = ((BloodrequestToBBfromHospital) workreq);

                row[1] = ((BloodrequestToBBfromHospital) workreq).getReqUnits();
                if (workreq.getStatus().equals("0")) {
                    row[2] = "In Process ";
                } else if (workreq.getStatus().equals("1")) {
                    row[2] = "In Progress";
                } else if (workreq.getStatus().equals("2")) {
                    row[2] = "Declined";
                } else if (workreq.getStatus().equals("3")) {
                    row[2] = "Completed";
                }
                try {
                    row[3] = workreq.getReceiver().getEmployee().getName();
                } catch (NullPointerException e) {

                    row[3] = "No Assignee yet";
                }
                row[4] = ((BloodrequestToBBfromHospital) workreq).senderEnterprise;
                model.addRow(row);
            }
        }

    }

    private void assignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignJButtonActionPerformed
        logger.log(Level.INFO, "assignJButtonActionPerformed --HospitalReqJPanel");

        int selectedRow = bloodReqTable.getSelectedRow();
        int rowCount = bloodReqTable.getSelectedRowCount();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a request", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (rowCount > 1) {
            JOptionPane.showMessageDialog(null, "Please select only one request", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        WorkRequest wq = (WorkRequest) bloodReqTable.getValueAt(selectedRow, 0);
        //        if(wq.getReceiver()!=null){
        //        JOptionPane.showMessageDialog(null, "Request has been processed earlier","warning",JOptionPane.WARNING_MESSAGE);
        //        return;
        //        }

        if (wq.getStatus().equals("1")) {
            JOptionPane.showMessageDialog(null, "The request is already in process", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (wq.getStatus().equals("3") || wq.getStatus().equals("2")) {
            JOptionPane.showMessageDialog(null, "Request has been completed earlier", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if ((wq).getStatus().equals("0")) {
            (wq).setReceiver(userAccount);
            (wq).setStatus("1");
            populateBloodReqTable();
            JOptionPane.showMessageDialog(null, "The request is now assigned to you! Kindly process it");
        }

    }//GEN-LAST:event_assignJButtonActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, "btnAcceptActionPerformed --HospitalReqJPanel");

        int selectedRow = bloodReqTable.getSelectedRow();
        int rowCount = bloodReqTable.getSelectedRowCount();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a request", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (rowCount > 1) {
            JOptionPane.showMessageDialog(null, "Please select only one request", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (rowCount == 1) {
            WorkRequest wq = (WorkRequest) bloodReqTable.getValueAt(selectedRow, 0);

            if (wq.getStatus().equals("0")) {
                JOptionPane.showMessageDialog(null, "The request has to be assigned first");
            } else if (wq.getStatus().equals("3") || wq.getStatus().equals("2")) {
                JOptionPane.showMessageDialog(null, "The request has been processed earlier");
            } else {
                String reqbloodgroup = ((BloodrequestToBBfromHospital) wq).getPatient().getBloodGroup();
                for (BloodGroup bg : this.bloodgrouplist.getBloodGroupList()) {
                    if (bg.getBloodgroup().equals(reqbloodgroup)) {
                        int AvailableUnits = Integer.parseInt(bg.getAvailableUnits());
                    }
                }
                int BorrowedUnits = ((BloodrequestToBBfromHospital) wq).getReqUnits();
                for (BloodGroup bg : this.bloodgrouplist.getBloodGroupList()) {
                    if (bg.getBloodgroup().equals(reqbloodgroup)) {
                        if (Integer.parseInt(bg.getAvailableUnits()) > BorrowedUnits) {
                            bg.setAvailableUnits(String.valueOf((Integer.parseInt(bg.getAvailableUnits()) - BorrowedUnits)));
                            JOptionPane.showMessageDialog(null, "Request has been accepted");
                            wq.setStatus("3");
                            populateBloodReqTable();
                            break;
                        } else {
                            JOptionPane.showMessageDialog(null, "Available Blood Units are lesser than the requested units, Please Decline the Request");
                        }
                    }
                }
            }
        }

    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnDeclineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeclineActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, "btnDeclineActionPerformed --HospitalReqJPanel");

        int selectedRow = bloodReqTable.getSelectedRow();
        int rowCount = bloodReqTable.getSelectedRowCount();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a request to be worked on", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (rowCount > 1) {
            JOptionPane.showMessageDialog(null, "Please select only one request", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        WorkRequest wq = (WorkRequest) bloodReqTable.getValueAt(selectedRow, 0);
        if (wq.getReceiver().equals(userAccount)) {
            if (wq.getStatus().equals("0")) {
                JOptionPane.showMessageDialog(null, "The request has to be assigned first");
            } else if (wq.getStatus().equals("3") || wq.getStatus().equals("2")) {
                JOptionPane.showMessageDialog(null, "The request has been processed earlier");
            } else {
                (wq).setReceiver(userAccount);
                (wq).setStatus("2");
                populateBloodReqTable();
                JOptionPane.showMessageDialog(null, "The request has been declined due to shortage of blood");

            }
        } else {
            JOptionPane.showMessageDialog(null, "The Request has to be processed by " + wq.getReceiver().getEmployee().getName());
        }
    }//GEN-LAST:event_btnDeclineActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
                logger.log(Level.INFO, "refreshJButtonActionPerformed --HospitalReqJPanel");

        populateBloodReqTable();

    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        logger.log(Level.INFO, "backJButtonActionPerformed --HospitalReqJPanel");

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ClinicianWorkAreaJPanel dwjp = (ClinicianWorkAreaJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JTable bloodReqTable;
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnDecline;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel manageEnt2;
    private javax.swing.JLabel manageEnt3;
    private javax.swing.JButton refreshJButton;
    // End of variables declaration//GEN-END:variables
}
